### ISSUE TITLE
Create a Pseudo Code

### ISSUE THREAD

**Issue by WoodlandHS-Robotics** [BeaverBots13601/CenterStage#2]

**Comment by GraysonTinker** [comment]
Locate AprilTag func
Thunk about apriltag data - find location, left right or center
Automated move to best position to place pixel on line
	- auto movement function like last year's action system
Place pixel on line
	- won't know how this works until build team figures their stuff out but most likely releasePixel() func
	- arm controlled by seperate class? seems very very very very ... very complicated
Automated move back to border
Go under the truss and through the backboard side, if needed
- IMPORTANT: Need some way to figure out if on backboard or audience side
Rotate towards backboard, move left while scanning for AprilTags
	- Move in chunks? Move @ slow pace while scanning every frame?
Once we find one AprilTag, we know the set distance to all the others
Move to appropriate apriltag for extra points
Place pixel if we can
Collision avoidance????
Park

**Comment by WoodlandHS-Robotics** [comment]
Once this is done, paste it into the [GitHub Wiki](https://github.com/BeaverBots13601/CenterStage/wiki/Pseudocode-&-Planning)

**Comment by alex-mckinley** [comment]
>   make sure we will not hit another robot

expand on this a bit more, but overall this looks good!

nit: as a formatting thing, write an if statement as if it were more code-like. for example 

`if: right - (rotate 90 move 0.5-0.2 foot forward)` 

becomes

```if tag = right
    rotate 90
    move .5-.2 feet forward
```

**Comment by alex-mckinley** [comment]
This looks good! Feel free to add it to the wiki. 

Also instead of just editing your comments, you can copy past and create new ones so I actually get notified of when things change
